---
title: "编译器错误 CS0156"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
f1_keywords: CS0156
helpviewer_keywords: CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
caps.latest.revision: "9"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 1a24aa212e8f8c1c8e03cdbe583f4c3f5a2e7de1
ms.sourcegitcommit: bd1ef61f4bb794b25383d3d72e71041a5ced172e
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/18/2017
---
# <a name="compiler-error-cs0156"></a>编译器错误 CS0156
在嵌套在最近的封闭 catch 子句内部的 finally 子句内不允许使用不带参数的 throw 语句  
  
 不带参数的 [throw](../../csharp/language-reference/keywords/throw.md) 语句只能出现在不带任何参数的 **catch** 子句中。  
  
 有关详细信息，请参阅[异常处理语句](../../csharp/language-reference/keywords/exception-handling-statements.md)和[异常和异常处理](../../csharp/programming-guide/exceptions/index.md)。  
  
 下面的示例生成 CS0156：  
  
```  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
