---
title: "&#39;Catch &#39;块永远不会达到的值，因为 &#39;&lt;name1&gt;&#39; 继承自 &#39;&lt;name2&gt;&#39;"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords: BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: "12"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: c21d4d662f4741916e308278a41a84d40f92454a
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 11/21/2017
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39;Catch &#39;块永远不会达到的值，因为 &#39;&lt;name1&gt;&#39; 继承自 &#39;&lt;name2&gt;&#39;
从未到达代码中的 `Catch` 块。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参阅[在 Visual Basic 中的配置警告](/visualstudio/ide/configuring-warnings-in-visual-basic)。  
  
 **错误 ID：** BC42029  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
-   删除无关的 `Catch` 块。  
  
## <a name="see-also"></a>另请参阅  
 [如何： 测试具有 Try 代码...在 Visual Basic 中 catch 块](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
